<script setup lang="ts">
import { ChevronRight, MessageCircle } from 'lucide-vue-next'
import type { Product } from '~/types/product'
type Detail = Product & { related: Product[] }
const route = useRoute()
const { data, error } = await useFetch<{ data: Detail }>(`/api/public/products/${route.params.slug}`)
if (error.value) throw createError({ statusCode: 404, statusMessage: 'Produk tidak ditemukan' })
const product = computed(() => data.value?.data)
const selected = ref(0)
const ui = useUiStore()
const { formatIDR } = useCurrency()
useSeoMeta({ title: () => `${product.value?.name || 'Produk'} | ProShop`, description: () => product.value?.shortDescription, ogImage: () => product.value?.coverImage.url })
</script>
<template><div v-if="product" class="container-main section"><div class="crumb"><NuxtLink to="/">Beranda</NuxtLink><ChevronRight :size="14"/><NuxtLink to="/produk">Produk</NuxtLink><ChevronRight :size="14"/><span>{{product.name}}</span></div><div class="detail"><div><NuxtImg class="main-image" :src="(product.images?.[selected]||product.coverImage).url" :alt="(product.images?.[selected]||product.coverImage).alt" width="900" height="700"/><div v-if="product.images && product.images.length>1" class="thumbs"><button v-for="(img,i) in product.images" :key="img.url" @click="selected=i"><NuxtImg :src="img.url" :alt="img.alt"/></button></div></div><div class="info"><span class="eyebrow">{{product.category.name}} · {{product.sku}}</span><h1 class="display">{{product.name}}</h1><strong class="price">{{formatIDR(product.price)}}</strong><ProductStockBadge :stock="product.stock" :threshold="product.lowStockThreshold"/><p>{{product.description}}</p><button class="btn btn-gold" @click="ui.orderProduct=product"><MessageCircle :size="18"/>{{product.stock?'Pesan via WhatsApp':'Tanya ketersediaan'}}</button><div class="spec"><h2>Spesifikasi</h2><dl><template v-for="(value,key) in product.specifications" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></template></dl></div></div></div><section v-if="product.related?.length" class="related"><h2 class="display">Produk terkait</h2><ProductGrid :products="product.related"/></section></div></template>
<style scoped>.crumb{display:flex;align-items:center;gap:.45rem;color:var(--muted);font-size:.76rem;margin-bottom:1.5rem}.detail{display:grid;grid-template-columns:1.1fr .9fr;gap:4rem}.main-image{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:16px;background:var(--surface)}.info{display:flex;flex-direction:column;align-items:flex-start;gap:1rem}.info h1{font-size:clamp(2.7rem,5vw,4.6rem);line-height:.95;margin:.4rem 0}.price{font-size:1.5rem}.info p{line-height:1.75;color:var(--muted)}.info>.btn{width:100%}.spec{width:100%;margin-top:1rem;border-top:1px solid var(--border);padding-top:1rem}.spec h2{font-size:1rem}.spec dl{margin:0}.spec dt,.spec dd{display:inline-block;width:50%;margin:0;padding:.6rem 0;border-bottom:1px solid var(--border);font-size:.85rem}.spec dt{color:var(--muted)}.thumbs{display:flex;gap:.5rem;margin-top:.7rem}.thumbs img{width:70px;height:55px;object-fit:cover;border-radius:8px}.related{margin-top:6rem}.related>h2{font-size:2.7rem}@media(max-width:800px){.detail{grid-template-columns:1fr;gap:2rem}.info>.btn{position:sticky;bottom:12px;z-index:5}.related{margin-top:4rem}}</style>
