-- DEMO ONLY: replace prices, stock, descriptions, and images before production use.
INSERT INTO categories(id,name,slug,sort_order) VALUES ('cat-bantal','Bantal','bantal',1),('cat-guling','Guling','guling',2),('cat-kasur','Kasur','kasur',3);
INSERT INTO products(id,category_id,sku,name,slug,short_description,description,price,stock,low_stock_threshold,specifications_json,is_featured) VALUES
('prod-1','cat-bantal','PS-BTL-001','Bantal Hotel Premium 900gr','bantal-hotel-premium-900gr','Bantal microfiber padat dengan permukaan lembut.','Dibuat untuk kebutuhan rumah dan penginapan.',89000,26,5,'{"Ukuran":"45 × 65 cm","Isi":"Microfiber","Berat":"± 900 gram"}',1),
('prod-2','cat-bantal','PS-BTL-002','Bantal Microfiber Standard','bantal-microfiber-standard','Bantal harian yang ringan dan empuk.','Pilihan praktis untuk kebutuhan harian.',69000,38,8,'{"Ukuran":"45 × 65 cm","Isi":"Microfiber"}',0),
('prod-3','cat-guling','PS-GLG-001','Guling Microfiber Premium','guling-microfiber-premium','Guling berisi padat dengan bentuk stabil.','Dirancang untuk menopang tubuh dengan nyaman.',79000,19,5,'{"Ukuran":"20 × 80 cm","Isi":"Microfiber"}',1),
('prod-4','cat-kasur','PS-KSR-001','Kasur Busa Single 90 × 200','kasur-busa-single-90x200','Kasur busa ukuran single.','Dukungan merata untuk kamar pribadi dan penginapan.',725000,7,3,'{"Ukuran":"90 × 200 cm","Material":"Busa padat"}',1),
('prod-5','cat-kasur','PS-KSR-002','Kasur Busa Double 160 × 200','kasur-busa-double-160x200','Kasur ukuran double dengan bidang tidur lega.','Pilihan nyaman untuk kebutuhan keluarga.',1250000,4,2,'{"Ukuran":"160 × 200 cm","Material":"Busa padat"}',0);
INSERT INTO product_images(id,product_id,image_url,alt_text,is_cover) VALUES
('img-1','prod-1','https://images.unsplash.com/photo-1620751852890-a89137ec78b9?auto=format&fit=crop&q=82&w=1200','Bantal Hotel Premium',1),('img-2','prod-2','https://images.unsplash.com/photo-1613618902610-95d88084ee11?auto=format&fit=crop&q=82&w=1200','Bantal Microfiber Standard',1),('img-3','prod-3','https://images.unsplash.com/photo-1613618902610-95d88084ee11?auto=format&fit=crop&q=82&w=1200','Guling Microfiber Premium',1),('img-4','prod-4','https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&q=82&w=1200','Kasur Busa Single',1),('img-5','prod-5','https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&q=82&w=1200','Kasur Busa Double',1);
INSERT INTO settings(key,value) VALUES ('business_name','ProShop'),('tagline','Produsen Bantal, Guling & Kasur'),('hero_eyebrow','PRODUK TIDUR BUATAN LOKAL'),('hero_title','Tidur lebih nyaman dimulai dari produk yang dibuat dengan benar.'),('hero_description','Bantal, guling, dan kasur produksi ProShop dengan pilihan ukuran, material, dan stok yang dapat langsung dikonsultasikan melalui WhatsApp.'),('hero_cta','Lihat Produk'),('service_hours','Senin–Sabtu, 08.00–17.00');
