<script setup lang="ts">
import { Menu, Search, X, MessageCircle } from 'lucide-vue-next'
const ui = useUiStore()
const { generalWhatsAppUrl } = useWhatsApp()
const search = ref('')
const links = [{ label: 'Beranda', to: '/' }, { label: 'Produk', to: '/produk' }, { label: 'Tentang', to: '/tentang' }, { label: 'Kontak', to: '/kontak' }]
ui.mobileNav = false
function submit() { navigateTo({ path: '/produk', query: { q: search.value || undefined } }) }
function close() { ui.mobileNav = false }
function onKeydown(event: KeyboardEvent) { if (event.key === 'Escape') close() }
watch(() => ui.mobileNav, (open) => { if (import.meta.client) document.body.style.overflow = open ? 'hidden' : '' })
onMounted(() => window.addEventListener('keydown', onKeydown))
onBeforeUnmount(() => { window.removeEventListener('keydown', onKeydown); document.body.style.overflow = '' })
</script>
<template><header><div class="container-main bar"><BrandLogo/><nav class="desktop-nav"><NuxtLink v-for="link in links" :key="link.to" :to="link.to">{{link.label}}</NuxtLink></nav><form class="search" @submit.prevent="submit"><Search :size="16"/><input v-model="search" aria-label="Cari produk" placeholder="Cari produk..."></form><a class="btn btn-gold wa" :href="generalWhatsAppUrl('header website ProShop')" target="_blank"><MessageCircle :size="17"/>WhatsApp</a><button class="mobile-trigger" aria-label="Buka menu" @click="ui.mobileNav=true"><Menu/></button></div></header><Teleport to="body"><Transition name="fade"><div v-if="ui.mobileNav" class="mobile-layer"><button class="backdrop" aria-label="Tutup menu" @click="close"/><aside class="drawer" aria-label="Navigasi mobile"><div class="drawer-head"><BrandLogo/><button aria-label="Tutup menu" @click="close"><X/></button></div><nav><NuxtLink v-for="link in links" :key="link.to" :to="link.to" @click="close">{{link.label}}</NuxtLink></nav><a class="btn btn-gold" :href="generalWhatsAppUrl('menu website ProShop')" target="_blank"><MessageCircle :size="18"/>Hubungi WhatsApp</a></aside></div></Transition></Teleport></template>
<style scoped>header{height:76px;position:sticky;top:0;z-index:40;background:#fffffff2;backdrop-filter:blur(10px);border-bottom:1px solid var(--border)}.bar{height:100%;display:flex;align-items:center;gap:1.5rem}.desktop-nav{display:flex;gap:1.5rem;margin-left:auto;font-size:.86rem;font-weight:650}.desktop-nav a.router-link-active{color:var(--gold-dark)}.search{display:flex;align-items:center;gap:.4rem;border:1px solid var(--border);border-radius:10px;padding:0 .65rem}.search input{border:0;outline:0;width:140px;height:38px}.mobile-trigger{display:none;margin-left:auto;padding:.55rem;border:0;background:none}.mobile-layer{position:fixed;z-index:200;inset:0;display:grid;grid-template-columns:minmax(0,1fr) min(390px,88vw)}.backdrop{grid-column:1;background:#17171780;border:0}.drawer{grid-column:2;background:white;padding:1.4rem;display:flex;flex-direction:column;box-shadow:-20px 0 60px #0003;min-width:0}.drawer-head{display:flex;align-items:center;justify-content:space-between;padding-bottom:1.5rem;border-bottom:1px solid var(--border)}.drawer-head button{display:grid;place-items:center;width:44px;height:44px;border:0;background:none}.drawer nav{display:flex;flex-direction:column;padding:1.5rem 0}.drawer nav a{padding:1rem 0;border-bottom:1px solid var(--border);font-size:1.05rem;font-weight:700}.drawer>.btn{margin-top:auto}.fade-enter-active,.fade-leave-active{transition:opacity .18s}.fade-enter-from,.fade-leave-to{opacity:0}@media(max-width:1020px){.desktop-nav,.search,.wa{display:none}.mobile-trigger{display:block}}</style>
