PRAGMA foreign_keys = ON;
CREATE TABLE admin_users (id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE admin_sessions (id TEXT PRIMARY KEY,admin_user_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(admin_user_id) REFERENCES admin_users(id));
CREATE TABLE login_attempts (id TEXT PRIMARY KEY,ip_hash TEXT NOT NULL,succeeded INTEGER NOT NULL DEFAULT 0,attempted_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE categories (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT,sort_order INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,deleted_at TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE products (id TEXT PRIMARY KEY,category_id TEXT,sku TEXT NOT NULL UNIQUE,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,short_description TEXT,description TEXT,price INTEGER NOT NULL DEFAULT 0 CHECK(price>=0),stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),low_stock_threshold INTEGER NOT NULL DEFAULT 5 CHECK(low_stock_threshold>=0),specifications_json TEXT NOT NULL DEFAULT '{}',is_featured INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,deleted_at TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE product_images (id TEXT PRIMARY KEY,product_id TEXT NOT NULL,image_url TEXT NOT NULL,storage_key TEXT,source TEXT NOT NULL DEFAULT 'r2',alt_text TEXT,sort_order INTEGER NOT NULL DEFAULT 0,is_cover INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE inventory_movements (id TEXT PRIMARY KEY,product_id TEXT NOT NULL,movement_type TEXT NOT NULL CHECK(movement_type IN('IN','OUT','ADJUSTMENT_IN','ADJUSTMENT_OUT')),quantity INTEGER NOT NULL CHECK(quantity>0),before_stock INTEGER NOT NULL CHECK(before_stock>=0),after_stock INTEGER NOT NULL CHECK(after_stock>=0),reference TEXT,counterparty TEXT,note TEXT,movement_at TEXT NOT NULL DEFAULT (datetime('now')),created_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(created_by) REFERENCES admin_users(id));
CREATE TABLE settings (key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE whatsapp_click_events (id TEXT PRIMARY KEY,product_id TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE audit_logs (id TEXT PRIMARY KEY,admin_user_id TEXT NOT NULL,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,metadata_json TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')),FOREIGN KEY(admin_user_id) REFERENCES admin_users(id));
CREATE TRIGGER validate_inventory_movement BEFORE INSERT ON inventory_movements BEGIN
  SELECT CASE WHEN NEW.before_stock != (SELECT stock FROM products WHERE id=NEW.product_id) THEN RAISE(ABORT,'STALE_STOCK') END;
  SELECT CASE WHEN NEW.movement_type IN ('IN','ADJUSTMENT_IN') AND NEW.after_stock != NEW.before_stock + NEW.quantity THEN RAISE(ABORT,'INVALID_STOCK_DELTA') END;
  SELECT CASE WHEN NEW.movement_type IN ('OUT','ADJUSTMENT_OUT') AND (NEW.quantity > NEW.before_stock OR NEW.after_stock != NEW.before_stock - NEW.quantity) THEN RAISE(ABORT,'INSUFFICIENT_STOCK') END;
END;
CREATE TRIGGER apply_inventory_movement AFTER INSERT ON inventory_movements BEGIN
  UPDATE products SET stock=NEW.after_stock,updated_at=datetime('now') WHERE id=NEW.product_id;
END;
CREATE INDEX idx_products_category_id ON products(category_id);CREATE INDEX idx_products_active_deleted ON products(is_active,deleted_at);CREATE INDEX idx_products_stock ON products(stock);CREATE INDEX idx_inventory_product_date ON inventory_movements(product_id,movement_at DESC);CREATE INDEX idx_inventory_type_date ON inventory_movements(movement_type,movement_at DESC);CREATE INDEX idx_whatsapp_created_at ON whatsapp_click_events(created_at DESC);CREATE INDEX idx_sessions_token ON admin_sessions(token_hash,expires_at);CREATE INDEX idx_login_attempts ON login_attempts(ip_hash,attempted_at DESC);
