import type { Product } from '../../app/types/product'
export const demoCategories=[{id:'cat-bantal',name:'Bantal',slug:'bantal'},{id:'cat-guling',name:'Guling',slug:'guling'},{id:'cat-kasur',name:'Kasur',slug:'kasur'}]
const pillow='https://images.unsplash.com/photo-1620751852890-a89137ec78b9?auto=format&fit=crop&q=82&w=1200'
const bedding='https://images.unsplash.com/photo-1613618902610-95d88084ee11?auto=format&fit=crop&q=82&w=1200'
const mattress='https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&q=82&w=1200'
export const demoProducts:Product[]=[
 {id:'prod-1',categoryId:'cat-bantal',sku:'PS-BTL-001',name:'Bantal Hotel Premium 900gr',slug:'bantal-hotel-premium-900gr',shortDescription:'Bantal microfiber padat dengan permukaan lembut untuk rumah dan penginapan.',description:'Dibuat dengan isi microfiber pilihan dan konstruksi yang menjaga bentuk tetap nyaman. Cocok untuk kebutuhan rumah, penginapan, maupun pemesanan dalam jumlah banyak.',price:89000,stock:26,lowStockThreshold:5,specifications:{Ukuran:'45 × 65 cm',Isi:'Microfiber',Berat:'± 900 gram',Cover:'Cotton blend'},isFeatured:true,isActive:true,category:demoCategories[0]!,coverImage:{url:pillow,alt:'Bantal Hotel Premium'},images:[{url:pillow,alt:'Bantal Hotel Premium'}]},
 {id:'prod-2',categoryId:'cat-bantal',sku:'PS-BTL-002',name:'Bantal Microfiber Standard',slug:'bantal-microfiber-standard',shortDescription:'Bantal harian yang ringan, empuk, dan mudah dirawat.',description:'Pilihan praktis untuk kebutuhan harian dengan komposisi isi yang seimbang.',price:69000,stock:38,lowStockThreshold:8,specifications:{Ukuran:'45 × 65 cm',Isi:'Microfiber',Cover:'Poly-cotton'},isFeatured:false,isActive:true,category:demoCategories[0]!,coverImage:{url:bedding,alt:'Bantal Microfiber Standard'},images:[{url:bedding,alt:'Bantal Microfiber Standard'}]},
 {id:'prod-3',categoryId:'cat-guling',sku:'PS-GLG-001',name:'Guling Microfiber Premium',slug:'guling-microfiber-premium',shortDescription:'Guling berisi padat dengan bentuk stabil dan balutan halus.',description:'Dirancang untuk menopang tubuh dengan nyaman dan mempertahankan bentuk.',price:79000,stock:19,lowStockThreshold:5,specifications:{Ukuran:'20 × 80 cm',Isi:'Microfiber',Cover:'Cotton blend'},isFeatured:true,isActive:true,category:demoCategories[1]!,coverImage:{url:bedding,alt:'Guling Microfiber Premium'},images:[{url:bedding,alt:'Guling Microfiber Premium'}]},
 {id:'prod-4',categoryId:'cat-kasur',sku:'PS-KSR-001',name:'Kasur Busa Single 90 × 200',slug:'kasur-busa-single-90x200',shortDescription:'Kasur busa ukuran single untuk ruang tidur yang efisien.',description:'Kasur busa dengan dukungan merata untuk kamar pribadi, kos, atau penginapan.',price:725000,stock:7,lowStockThreshold:3,specifications:{Ukuran:'90 × 200 cm',Material:'Busa padat',Produksi:'ProShop'},isFeatured:true,isActive:true,category:demoCategories[2]!,coverImage:{url:mattress,alt:'Kasur Busa Single'},images:[{url:mattress,alt:'Kasur Busa Single'}]},
 {id:'prod-5',categoryId:'cat-kasur',sku:'PS-KSR-002',name:'Kasur Busa Double 160 × 200',slug:'kasur-busa-double-160x200',shortDescription:'Kasur ukuran double dengan bidang tidur lega.',description:'Pilihan nyaman untuk kebutuhan keluarga dengan ukuran yang dapat dikonsultasikan.',price:1250000,stock:4,lowStockThreshold:2,specifications:{Ukuran:'160 × 200 cm',Material:'Busa padat',Produksi:'ProShop'},isFeatured:false,isActive:true,category:demoCategories[2]!,coverImage:{url:mattress,alt:'Kasur Busa Double'},images:[{url:mattress,alt:'Kasur Busa Double'}]}
]
